# RETE INTERNA (LAN AZIENDALE)
host1[0]=LAN
switch1[1]=LAN

#COLLEGAMENTO SWITCH -> ROUTER (DMZ)

switch1[2]=DMZ
router1[0]=DMZ

# RETE ESTERNA (INTERNET)
router1[1]=WAN
internet[0]=WAN

# PIANO DI CONTROLLO (Switch <-> Controller)
switch1[0]=CTRL
controller1[0]=CTRL

# IMMAGINI DOCKER
host1[image]="sdn-custom"
switch1[image]="sdn-custom"
router1[image]="sdn-custom"
internet[image]="sdn-custom"
controller1[image]="sdn-custom"


