# SDN FIREWALL PROJECT CONFIGURATION - SCALABLE TOPOLOGY


#	HOW TO READ THIS FILE (QUICK GUIDE AND GLOSSARY)

# 1) KATHARA SYNTAX:
#	The format 'node[port]=domain' connects a specific
#	network interface of a machine to a virtual cable.
#	Ex: firewall[2]=TRUNK1 means "interface eth2 of the
#	firewall is connected to the collision domain TRUNK1"

# 2) NETWORK ZONES & TERMINOLOGY:
#	-CTRL:	Dedicated Out-of-Band network for the SDN Control Plane.
#		Allows the Ryu controller to communicate with the firewall.
#	-TRUNK (1 & 2): REdunadnt physical links connecting the firewall
#		and the L2 switch. Managed by STP to prevent loops.
#	-VLANs:	Logical segemntation of the internal network:
#		* VLAN10: IT Department (Privileged access)
#		* VLAN20: Marketing Department
#		* VLAN30: DMZ (Web Server exposed to the Internet)
#		* VLAN40: Data Zone (Private Database, no Internet access)
#	- FW_RT & WAN: Transit domain for external routing

# 3) CUSTOM IMAGED:
#	The directive note[image="sdn-custom" instructs Kathara
#	to use our custom Docker image containing Ryu and Open vSwtich

# BEGIN OF CODE PART:

# SDN CONTROL (Ryu Controller)
controller[0]=CTRL
firewall[0]=CTRL

# ROUTER <-> FIREWALL CONNECTION
# Traffic passes from the router to the firewall for inspection
router[0]=FW_RT
firewall[1]=FW_RT


# REDUNDANCY (Dual link STP) FIREWALL <-> SWITCH
#Two distinct physical cables managed by the Spanning Tree Protocol
firewall[2]=TRUNK1
switch[0]=TRUNK1

firewall[3]=TRUNK2
switch[1]=TRUNK2

# VLAN 10: IT DEPARTMENT
# Switch port 3 manages the entire IT  department
switch[2]=VLAN10
it_dept1[0]=VLAN10

# Delete next comments to add more users in it department, you need to add the relative files where you configure them.
#	it_dept2[0]=VLAN10
#	it_dept3[0]=VLAN10

# VLAN 20: MARKETING 
# Switch port 4 manages the entire marketing department
switch[3]=VLAN20
marketing1[0]=VLAN20

# Delete next comments to add more users in marketing department, you need to add the relative files where you configure them.
#	marketing2[0]=VLAN20
#	marketing3[0]=VLAN20

# VLAN 30: SERVER ZONE (DMZ)
# Only the web server lives here, exposed to the Internet
switch[4]=VLAN30
web_server[0]=VLAN30

# VLAN 40: DATA ZONE (Database)
# Private zone, no direct access from the Internet
switch[5]=VLAN40
db_server[0]=VLAN40

# EXTERNAL NETWORK (Internet)
router[1]=WAN
internet[0]=WAN

# DOCKER IMAGE ASSIGNMENT SECTION

# Network nodes images
switch[image]="sdn-custom"
firewall[image]="sdn-custom"
router[image]="sdn-custom"
internet[image]="sdn-custom"
controller[image]="sdn-custom"

# Corporate host images
it_dept1[image]="sdn-custom"
marketing1[image]="sdn-custom"
web_server[image]="sdn-custom"
db_server[image]="sdn-custom"

# Additional host images (Uncomment if nodes aboev are activated)

#	it_dept2[image]="sdn-custom"
#	it_dept3[image]="sdn-custom"
#	marketing2[image]="sdn-custom"
#	marketing3[image]="sdn-custom"
